### ISSUE TITLE
More succinct Director documentation?

### ISSUE THREAD

**Issue by hiremaga** [cloudfoundry-attic/cf-docs#129]
https://github.com/cloudfoundry/cf-docs/blob/master/source/docs/running/bosh/components/director.html.md

The page above goes into excruciating detail about the implementation details of a Director. Who is the intended audience for this page?

In my opinion some of the implementation details on this page (e.g. Reference to *Manager classes and specific Model objects) are likely to change frequently (even if they haven't in the past).

I'd suggest rewriting this page with a BOSH Release Deployer in mind.

**Comment by hiremaga** [comment]
Here's a question since I'm relatively new to BOSH. Is it realistic to expect somebody to use the Director API directly or will this always be via the BOSH CLI? 

If there are in fact examples of people using the Director API directly, maybe some of the information on this page could be expressed in terms of the API only, rather than its current implementation (e.g. *Managers).

This might also be a good candidate for conversion to [inline documentation](https://github.com/cloudfoundry/bosh/pull/252) eventually.

**Comment by mstine** [comment]
So yeah, I think I agree with you. The audience for this stuff, which ultimately becomes docs.cloudfoundry.com, is composed of release developers and deployers. This page could be recomposed in terms of API endpoints rather than "managers." That said, much of this particular page could be eliminated simply by introducing Swagger UI and keeping the associated JSON up-to-date with in source annotations on director.rb.

I think we don't want to discount people using the Director API directly. For example, BOSH currently doesn't have a web UI. I could see a team wanting to develop an operations portal that used the Director API to get stuff done (in fact, I've considered working on something like this myself as a way to learn the director better).

**Comment by jfoley** [comment]
@hiremaga - can we close this? It looks like the docs are moving in that direction.

@aramprice / @jfoley

**Comment by hiremaga** [comment]
Yes, please close. Thanks!
