### ISSUE TITLE
cf delete-user

### ISSUE THREAD

**Issue by chbussler** [cloudfoundry-attic/cf-docs#190]
Hi,

cf delete-user

1) is in the detailed section of http://docs.cloudfoundry.com/docs/using/managing-apps/cf/
2) but not in the index section of http://docs.cloudfoundry.com/docs/using/managing-apps/cf/
3) and not implemented; cf delete-user is not known to cf

Esp. 3) is a bit confusing.

Christoph

**Comment by mark-rushakoff** [comment]
Our documentation team is going to fix that soon.  Thanks for bringing it up!

@mark-rushakoff / @matthewmcnew

**Comment by adamstegman** [comment]
@chbussler We are going to go ahead and close this issue because specific commands like `delete-user` are no longer documented.

For future requests, please open issues or pull requests against the new CLI docs repo: https://github.com/cloudfoundry/docs-dev-guide.

Thanks,
CF Community Pair (@adamstegman & @mbhave)
